name: Example iOS Build

on: 
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: fastlane run build_app
      
