name: Example iOS Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and release iOS app
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
