name: Test1
on: 
      push:
        branches: [main]
jobs:
      build:
        runs-on: [macos-latest]
        env:
          XC_VERSION: ${{ '11.4.1' }}
          XC_PROJECT: ${{ 'Test1.xcodeproj' }}
          XC_SCHEME: ${{ 'Test1' }}
        steps:
        - name: Select latest Xcode
          run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
        - uses: actions/checkout@v2
        - name: Run Unit and UI Tests
          run: /usr/bin/xcodebuild test -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'
          
