name: Test1
on: 
  push:
    branches: main
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Init
      run: |
        currentAgentPath=$(dirname $(dirname $RUNNER_WORKSPACE))
        targetAgentPath="/Users/runner/runners/current"
        ln -s $currentAgentPath $targetAgentPath
