name: react-native-ios-build-ipa
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XCODE_VERSION: ${{ '11.4.1' }}
      XCODE_PROJECT: ${{ 'Test1.xcodeproj' }}
      XCODE_SCHEME: ${{ 'Test1' }}
      XCODE_EXPORT_PATH: ${{ './artifacts' }}
      XCODE_KEYCHAIN: ${{ 'temporary.keychain' }}

      CERT_FILE: ${{ '.github/secrets/ios_distribution.p12' }}
      PROV_FILE: ${{ '.github/secrets/Test1.mobileprovision'}}
      CERT_FILE_GPG: ${{ '.github/secrets/ios_distribution.p12.gpg' }}
      PROV_FILE_GPG: ${{ '.github/secrets/Test1.mobileprovision.gpg'}}

      CERT_PASS: ${{ secrets.CERTS_PWD }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: install package
      run: |
        npm install
        #npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
        cd ios && pod install --repo-update && cd ..

    - name: install codesign
      run: |
        gpg -d -o "$CERT_FILE" --pinentry-mode=loopback --passphrase "$CERT_PASS" "$CERT_FILE_GPG"
        gpg -d -o "$PROV_FILE" --pinentry-mode=loopback --passphrase "$CERT_PASS" "$PROV_FILE_GPG"

        security create-keychain -p "" "$XCODE_KEYCHAIN"
        security list-keychains -s "$XCODE_KEYCHAIN"
        security default-keychain -s "$XCODE_KEYCHAIN"
        security unlock-keychain -p "" "$XCODE_KEYCHAIN"
        security set-keychain-settings
        #security set-keychain-settings "$XCODE_KEYCHAIN"
        #security import "$CERT_FILE" -k "$XCODE_KEYCHAIN" -P "$CERT_PASS" -T "/usr/bin/codesign"
        #security set-key-partition-list -S apple-tool:,apple: -s -k "" "$XCODE_KEYCHAIN"

        mkdir -p "~/Library/MobileDevice/Provisioning Profiles"
        cp "$PROV_FILE" "~/Library/MobileDevice/Provisioning Profiles"

    - name: Archive 
      run: |
        #mkdir artifacts

        cd ios

        #xcodebuild archive -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" -configuration release -archivePath "$XCODE_SCHEME.xcarchive"
        #xcodebuild archive -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" -configuration release -archivePath "$XCODE_SCHEME.xcarchive" code_sign_style="manual"
        #xcodebuild archive -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" code_sign_identity="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        xcodebuild archive -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" -configuration release code_sign_identity="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        #xcodebuild build -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" code_sign_identity="" code_signing_required=no code_signing_allowed=no
        #xcodebuild build -project "$XCODE_SCHEME.xcodeproj" -scheme "$XCODE_SCHEME" code_sign_identity="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
