name: Example iOS Build

on: 
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      #- uses: actions/checkout@v2
      
      - name: configure ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install fastlane & plugins
        run: bundle install
      
