#https://betterprogramming.pub/deploy-an-ios-app-to-testflight-or-the-app-store-using-github-actions-c4d7082b1430

name: react-native-ios-build-ipa
on: 
  push:
    branches: main
jobs:
  build:
    runs-on: macos-latest
    env:
      XCODE_VERSION: ${{ '11.4.1' }}
      XCODE_PROJECT: ${{ 'Test1.xcodeproj' }}
      XCODE_SCHEME: ${{ 'Test1' }}
      XCODE_EXPORT_PATH: ${{ './artifacts' }}

      KEYCHAIN_FILE: ${{ '/tmp/temp.keychain' }}

      CERT_FILE: ${{ '.github/secrets/ios_distribution.p12' }}
      PROV_FILE: ${{ '.github/secrets/Test1.mobileprovision'}}
      CERT_FILE_GPG: ${{ '.github/secrets/ios_distribution.p12.gpg' }}
      PROV_FILE_GPG: ${{ '.github/secrets/Test1.mobileprovision.gpg'}}

      CERT_PASS: ${{ secrets.CERTS_PWD }}
    steps:
    #- name: Select latest Xcode
    #  run: sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app

    - name: checkout
      uses: actions/checkout@v2

    - name: configure node
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: configure ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: "2.x"

    - name: install fastlane & plugins
      run: bundle install
