name: react-native-ios-build-ipa
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: [macos-latest]
    env:
      KEYCHAIN_FILE = ${{ RUNNER_TEMP }}
    steps:
    - name: Configure Codesign
      run: |
        echo $KEYCHAIN_FILE+'/temp.keychain'
